// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ErinWang666/image-processor/internal/domain (interfaces: ImageRepository)
//
// Generated by this command:
//
//	mockgen -destination internal/usecase/mocks/mock_repo2.go -package mocks github.com/ErinWang666/image-processor/internal/domain ImageRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ErinWang666/image-processor/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockImageRepository is a mock of ImageRepository interface.
type MockImageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockImageRepositoryMockRecorder
	isgomock struct{}
}

// MockImageRepositoryMockRecorder is the mock recorder for MockImageRepository.
type MockImageRepositoryMockRecorder struct {
	mock *MockImageRepository
}

// NewMockImageRepository creates a new mock instance.
func NewMockImageRepository(ctrl *gomock.Controller) *MockImageRepository {
	mock := &MockImageRepository{ctrl: ctrl}
	mock.recorder = &MockImageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageRepository) EXPECT() *MockImageRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockImageRepository) GetByID(ctx context.Context, id string) (*domain.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockImageRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockImageRepository)(nil).GetByID), ctx, id)
}

// GetPendingOutboxMessages mocks base method.
func (m *MockImageRepository) GetPendingOutboxMessages(ctx context.Context, limit int) ([]*domain.OutboxMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingOutboxMessages", ctx, limit)
	ret0, _ := ret[0].([]*domain.OutboxMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingOutboxMessages indicates an expected call of GetPendingOutboxMessages.
func (mr *MockImageRepositoryMockRecorder) GetPendingOutboxMessages(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingOutboxMessages", reflect.TypeOf((*MockImageRepository)(nil).GetPendingOutboxMessages), ctx, limit)
}

// MarkOutboxAsSent mocks base method.
func (m *MockImageRepository) MarkOutboxAsSent(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutboxAsSent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkOutboxAsSent indicates an expected call of MarkOutboxAsSent.
func (mr *MockImageRepositoryMockRecorder) MarkOutboxAsSent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutboxAsSent", reflect.TypeOf((*MockImageRepository)(nil).MarkOutboxAsSent), ctx, id)
}

// Save mocks base method.
func (m *MockImageRepository) Save(ctx context.Context, img *domain.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, img)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockImageRepositoryMockRecorder) Save(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockImageRepository)(nil).Save), ctx, img)
}

// UpdateResult mocks base method.
func (m *MockImageRepository) UpdateResult(ctx context.Context, id string, status domain.ImageStatus, thumbnailURL string, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResult", ctx, id, status, thumbnailURL, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateResult indicates an expected call of UpdateResult.
func (mr *MockImageRepositoryMockRecorder) UpdateResult(ctx, id, status, thumbnailURL, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResult", reflect.TypeOf((*MockImageRepository)(nil).UpdateResult), ctx, id, status, thumbnailURL, tags)
}

// UpdateStatus mocks base method.
func (m *MockImageRepository) UpdateStatus(ctx context.Context, id string, status domain.ImageStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockImageRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockImageRepository)(nil).UpdateStatus), ctx, id, status)
}

// UpdateStatusWithOutbox mocks base method.
func (m *MockImageRepository) UpdateStatusWithOutbox(ctx context.Context, id string, status domain.ImageStatus, topic string, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusWithOutbox", ctx, id, status, topic, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusWithOutbox indicates an expected call of UpdateStatusWithOutbox.
func (mr *MockImageRepositoryMockRecorder) UpdateStatusWithOutbox(ctx, id, status, topic, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusWithOutbox", reflect.TypeOf((*MockImageRepository)(nil).UpdateStatusWithOutbox), ctx, id, status, topic, payload)
}
