// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ErinWang666/image-processor/internal/domain (interfaces: AIService)
//
// Generated by this command:
//
//	mockgen -destination internal/usecase/mocks/mock_ai.go -package mocks github.com/ErinWang666/image-processor/internal/domain AIService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAIService is a mock of AIService interface.
type MockAIService struct {
	ctrl     *gomock.Controller
	recorder *MockAIServiceMockRecorder
	isgomock struct{}
}

// MockAIServiceMockRecorder is the mock recorder for MockAIService.
type MockAIServiceMockRecorder struct {
	mock *MockAIService
}

// NewMockAIService creates a new mock instance.
func NewMockAIService(ctrl *gomock.Controller) *MockAIService {
	mock := &MockAIService{ctrl: ctrl}
	mock.recorder = &MockAIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIService) EXPECT() *MockAIServiceMockRecorder {
	return m.recorder
}

// GenerateTags mocks base method.
func (m *MockAIService) GenerateTags(ctx context.Context, imageData []byte) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTags", ctx, imageData)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTags indicates an expected call of GenerateTags.
func (mr *MockAIServiceMockRecorder) GenerateTags(ctx, imageData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTags", reflect.TypeOf((*MockAIService)(nil).GenerateTags), ctx, imageData)
}
