// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ErinWang666/image-processor/internal/domain (interfaces: TaskLocker)
//
// Generated by this command:
//
//	mockgen -destination internal/usecase/mocks/mock_locker.go -package mocks github.com/ErinWang666/image-processor/internal/domain TaskLocker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskLocker is a mock of TaskLocker interface.
type MockTaskLocker struct {
	ctrl     *gomock.Controller
	recorder *MockTaskLockerMockRecorder
	isgomock struct{}
}

// MockTaskLockerMockRecorder is the mock recorder for MockTaskLocker.
type MockTaskLockerMockRecorder struct {
	mock *MockTaskLocker
}

// NewMockTaskLocker creates a new mock instance.
func NewMockTaskLocker(ctrl *gomock.Controller) *MockTaskLocker {
	mock := &MockTaskLocker{ctrl: ctrl}
	mock.recorder = &MockTaskLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskLocker) EXPECT() *MockTaskLockerMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockTaskLocker) Acquire(ctx context.Context, key string, ttl time.Duration) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, key, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Acquire indicates an expected call of Acquire.
func (mr *MockTaskLockerMockRecorder) Acquire(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockTaskLocker)(nil).Acquire), ctx, key, ttl)
}

// Release mocks base method.
func (m *MockTaskLocker) Release(ctx context.Context, key, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, key, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockTaskLockerMockRecorder) Release(ctx, key, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockTaskLocker)(nil).Release), ctx, key, token)
}
