// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ErinWang666/image-processor/internal/interface/http (interfaces: ImageUsecase)
//
// Generated by this command:
//
//	mockgen -destination internal/interface/http/mocks/mock_usecase.go -package mocks github.com/ErinWang666/image-processor/internal/interface/http ImageUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ErinWang666/image-processor/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockImageUsecase is a mock of ImageUsecase interface.
type MockImageUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockImageUsecaseMockRecorder
	isgomock struct{}
}

// MockImageUsecaseMockRecorder is the mock recorder for MockImageUsecase.
type MockImageUsecaseMockRecorder struct {
	mock *MockImageUsecase
}

// NewMockImageUsecase creates a new mock instance.
func NewMockImageUsecase(ctrl *gomock.Controller) *MockImageUsecase {
	mock := &MockImageUsecase{ctrl: ctrl}
	mock.recorder = &MockImageUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageUsecase) EXPECT() *MockImageUsecaseMockRecorder {
	return m.recorder
}

// ConfirmTask mocks base method.
func (m *MockImageUsecase) ConfirmTask(ctx context.Context, imageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmTask", ctx, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmTask indicates an expected call of ConfirmTask.
func (mr *MockImageUsecaseMockRecorder) ConfirmTask(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmTask", reflect.TypeOf((*MockImageUsecase)(nil).ConfirmTask), ctx, imageID)
}

// CreateTask mocks base method.
func (m *MockImageUsecase) CreateTask(ctx context.Context, img *domain.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, img)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockImageUsecaseMockRecorder) CreateTask(ctx, img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockImageUsecase)(nil).CreateTask), ctx, img)
}

// GetImage mocks base method.
func (m *MockImageUsecase) GetImage(ctx context.Context, id string) (*domain.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, id)
	ret0, _ := ret[0].(*domain.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockImageUsecaseMockRecorder) GetImage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockImageUsecase)(nil).GetImage), ctx, id)
}
